package com.sagar.selectiverecycleviewinbottomsheetdialog

import com.sagar.selectiverecycleviewinbottonsheetdialog.model.SelectionListObject

object DataList {

    val roleList = arrayListOf(
        SelectionListObject("1", "Developer", false),
        SelectionListObject("2", "Team Lead", false),
        SelectionListObject("3", "Senior Manager", false),
        SelectionListObject("4", "Project Manager", false),
        SelectionListObject("5", "CTO", false),
        SelectionListObject("6", "CEO", false),
        SelectionListObject("7", "Business Analyst", false),
        SelectionListObject("8", "Quality Analyst", false),
        SelectionListObject("9", "HR Manager", false),
        SelectionListObject("10", "Marketing Manager", false),
        SelectionListObject("11", "Sales Manager", false),
        SelectionListObject("12", "Finance Manager", false),
        SelectionListObject("13", "Operations Manager", false),
        SelectionListObject("14", "Customer Support", false),
        SelectionListObject("15", "IT Support", false),
        SelectionListObject("16", "Network Administrator", false),
        SelectionListObject("17", "System Administrator", false),
        SelectionListObject("18", "DevOps Engineer", false),
        SelectionListObject("19", "Cloud Architect", false),
        SelectionListObject("20", "Data Scientist", false),
        SelectionListObject("21", "Database Administrator", false),
        SelectionListObject("22", "Security Analyst", false),
        SelectionListObject("23", "UI/UX Designer", false),
        SelectionListObject("24", "Mobile App Developer", false),
        SelectionListObject("25", "Web Developer", false),
        SelectionListObject("26", "Full Stack Developer", false)
    )

    val cityList = arrayListOf(
        SelectionListObject("1", "Pune", false),
        SelectionListObject("2", "Bangalore", false),
        SelectionListObject("3", "Mumbai", false),
        SelectionListObject("4", "Chennai", false),
        SelectionListObject("5", "Kolkata", false),
        SelectionListObject("6", "Nashik", false),
        SelectionListObject("7", "Noida", false),
        SelectionListObject("8", "Jaipur", false),
        SelectionListObject("9", "Lucknow", false),
        SelectionListObject("10", "Ahmedabad", false),
        SelectionListObject("11", "Hyderabad", false),
        SelectionListObject("12", "Delhi", false),
        SelectionListObject("13", "Kanpur", false),
        SelectionListObject("14", "Patna", false),
        SelectionListObject("15", "Surat", false),
        SelectionListObject("16", "Visakhapatnam", false),
        SelectionListObject("17", "Nagpur", false),
        SelectionListObject("18", "Bhopal", false),
        SelectionListObject("19", "Indore", false),
        SelectionListObject("20", "Chandigarh", false),
        SelectionListObject("21", "Guwahati", false),
        SelectionListObject("22", "Kochi", false),
        SelectionListObject("23", "Trivandrum", false),
        SelectionListObject("24", "Bhubaneswar", false),
        SelectionListObject("25", "Goa", false),
        SelectionListObject("26", "Vadodara", false),
        SelectionListObject("27", "Agra", false),
        SelectionListObject("28", "Varanasi", false),
        SelectionListObject("29", "Madurai", false),
        SelectionListObject("30", "Jodhpur", false),
        SelectionListObject("36", "Coimbatore", false),
        SelectionListObject("37", "Mysore", false),
        SelectionListObject("38", "Vijayawada", false),
        SelectionListObject("39", "Raipur", false),
        SelectionListObject("40", "Ranchi", false),
        SelectionListObject("41", "Bareilly", false),
        SelectionListObject("42", "Bhatinda", false),
        SelectionListObject("43", "Dehradun", false),
    )

}